server:
  port: 8081

spring:
  application:
    name: microserviceServerConfig
  cloud:
    config:
      server:
        git:
          search-paths: microserviceServerAdmin,learningSpringboot,learningMongo
          uri: https://github.com/karpoora/config-repository
          username: sundarapandiank@yahoo.com
          clone-on-start: true
          password: Karnan22@

security:
  basic:
    enabled: false
  ignored:
    - console/**
    - health

management:
  security:
    enabled: false

