spring:
  cloud:
    config:
      server:
        git:
          search-paths: email-service,server-admin,gateway-service,register-service,server-zipkin
          uri: https://github.com/karpoora/config-repository
          username: sundarapandiank@yahoo.com
          clone-on-start: true
          password: Karnan22@

security:
  basic:
    enabled: false



