server:
  port: 8081

spring:
  boot:
    admin:
      discovery:
        services: server-admin
  cloud:
    config:
      server:
        git:
          search-paths: server-admin,summation-service,learningMongo
          uri: https://github.com/karpoora/config-repository
          username: sundarapandiank@yahoo.com
          clone-on-start: true
          password: Karnan22@
  application:
    admin:
      enabled: true

security:
  basic:
    enabled: false
  ignored:
    - console/**
    - health

management:
  security:
    enabled: false


