server:
  port: 9002

spring:
  boot:
    admin:
      url: http://localhost:8082
  application:
    name: ServiceConfig
  cloud:
    config:
      server:
        git:
          search-paths: learningSpringbootAdmin,learningSpringboot,learningMongo
          uri: https://github.com/karpoora/config-repository
          username: sundarapandiank@yahoo.com
          clone-on-start: true
          password: ******

security:
  basic:
    enabled: false
  ignored:
    - console/**
    - health

management:
  security:
    enabled: false

